version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
  # Add and entry for every directory to check
  #- package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    #directory: "/src/http/get-index"
    # Check the npm registry for updates every day (weekdays)
    #schedule:
      #interval: "daily"
